import { useEffect, useState } from "react";
import { ArrowUpRight } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../../api/client.js";

const cards = [{ key: "weddings", label: "Weddings", link: "/admin/weddings" }, { key: "photos", label: "Photos", link: "/admin/gallery" }, { key: "inquiries", label: "Inquiries", link: "/admin/inquiries" }, { key: "upcomingBookings", label: "Upcoming bookings", link: "/admin/bookings" }, { key: "testimonials", label: "Testimonials", link: "/admin/testimonials" }, { key: "packages", label: "Packages", link: "/admin/packages" }];
export default function AdminDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { api.get("/api/admin/dashboard").then(({ data: response }) => setData(response)).catch(() => setError("Dashboard data could not be loaded.")); }, []);
  if (error) return <section className="min-h-screen bg-[#090909] p-10 text-white"><p className="text-red-300">{error}</p></section>;
  if (!data) return <section className="min-h-screen bg-[#090909] p-10 text-white"><p className="text-[#c6a75e]">Loading studio pulse…</p></section>;
  return <section className="min-h-screen bg-[#090909] p-5 text-white md:p-10"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.3em] text-[#c6a75e]">Good morning, studio</p><h1 className="mt-2 font-serif text-5xl">Your command center.</h1><p className="mt-3 text-sm text-white/40">A live view of the work, stories and relationships moving through WeddingBingo.</p></div><span className="text-xs uppercase tracking-widest text-white/30">{new Date().toLocaleDateString()}</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ key, label, link }) => <Link key={key} to={link} className="group rounded-2xl border border-white/10 bg-white/[.03] p-5 transition hover:-translate-y-1 hover:border-[#c6a75e]/50"><div className="flex items-start justify-between"><span className="grid h-6 w-6 place-items-center rounded-full border border-[#c6a75e]/50 text-xs text-[#c6a75e]">{label.slice(0, 1)}</span><ArrowUpRight size={16} className="text-white/25 transition group-hover:text-[#c6a75e]" /></div><p className="mt-8 text-4xl font-light">{data.stats[key] || 0}</p><p className="mt-1 text-xs uppercase tracking-widest text-white/40">{label}</p></Link>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-serif text-2xl">Recent inquiries</h2><Link to="/admin/inquiries" className="text-xs text-[#c6a75e]">View all</Link></div>{data.recentInquiries.length ? data.recentInquiries.map((item) => <div key={item._id} className="flex items-center justify-between border-t border-white/10 py-4"><div><p className="text-sm">{item.name}</p><p className="mt-1 text-xs text-white/35">{item.email}</p></div><span className="rounded-full bg-[#c6a75e]/10 px-3 py-1 text-[10px] uppercase tracking-widest text-[#c6a75e]">{item.status}</span></div>) : <p className="text-sm text-white/35">No inquiries yet.</p>}</div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-serif text-2xl">Upcoming bookings</h2><Link to="/admin/bookings" className="text-xs text-[#c6a75e]">View all</Link></div>{data.upcomingBookings.length ? data.upcomingBookings.map((item) => <div key={item._id} className="flex items-center justify-between border-t border-white/10 py-4"><div><p className="text-sm">{item.coupleNames}</p><p className="mt-1 text-xs text-white/35">{item.venue || item.location || "Location not set"}</p></div><span className="text-xs text-white/45">{item.weddingDate ? new Date(item.weddingDate).toLocaleDateString() : "Date pending"}</span></div>) : <p className="text-sm text-white/35">No upcoming bookings.</p>}</div></div></div></section>;
}
